sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install pytest
- pip install pytest-cov
- pip install requests
- pip install scrutinizer-ocular
- pip install codecov
before_script:
- export QINIU_TEST_BUCKET="pythonsdk"
- export QINIU_TEST_DOMAIN="pythonsdk.qiniudn.com"
- export QINIU_TEST_ENV="travis"
- export PYTHONPATH="$PYTHONPATH:."
script:
- if [[ "$TRAVIS_PYTHON_VERSION" != "2.6.9" ]]; then flake8 --show-source --max-line-length=160
  .; fi
- py.test --cov qiniu
- if [[ "$TRAVIS_PYTHON_VERSION" != "2.6.9" ]]; then ocular --data-file .coverage;
  fi
- coverage run test_qiniu.py
env:
  global:
    - secure: "azupHFP4JeGrTgHYDzUAVlQsjEWw4r34us6Jb+ISPRDysHSKNAJr8wp/aXkC6WjwJ2vCE0XZuK3Epqjo/wdu6e8HhWmTwPAkM2C613XQKE68AucvvVms28FbFMgXMii1wxQTcvFXDa7c9muyXTYKYZk5BQGvJ+aR98NSJ540utbsIHxsM16o9KIoUliEfnPW6esjf5cRiN6Wk9MDtu7knmigKG4M5RHcHb4mkLUOyQMyz78v8JT+2ne6Csax3cEp+wpxJJQzwSsBAtfSPUHP4UEs73mnJSn8MAxx6pOTftKo4cLtZHejRLIisR+Kr8TcxDb4weiy8VtRDEnL3j2A/3VI/fKfyKLfJQlqNOm0w6rH12klxRSXekENYoOn1aYVS3GG678X+c+G6cDxWud6W5wMigmbKxKeWiSaxfLNyYJf7kPrx1johJxwXvzNr6EMrGmOOsInsuhx2Sauh2MKvK8RtQgtu/NHUT2AIwgcJOWX16S2vsL+TPT2eiq23SXcWY7ZZKMwJHq8v3oTUc+0Rz21ptCjTUTGatfUmgXVHYd5qLiMqjbu/LdlyBb2a6dwv3kr3PF24y0At30wyWfT59xB4/+sLimmcKCkKAgzrJyn/En0w4nL2Mudx23zVly2EX0xB5YYfwkBpQf1ysGsIjbTEOojUe6KgfsuoEn+CLY="
    - QINIU_ACCESS_KEY=vHg2e7nOh7Jsucv2Azr5FH6omPgX22zoJRWa0FN5

after_success:
  - codecov
